namespace dezi.Input
{
    public enum InputAction
    {
        None,
        MoveCursorUp,
        MoveCursorDown,
        MoveCursorLeft,
        MoveCursorRight,
        Home,
        End,
        PageUp,
        PageDown,
        Tab,
        AddCursorOverFirst,
        AddCursorUnderLast,
        QuitUiElement,
        QuitProgram,
        Delete,
        Backspace,
        AddNewLine,
        Input,
        Replace,
        Copy,
        Paste,
        Save,
        SpawnMultiCursorAbove,
        SpawnMultiCursorUnder,
        DeactivateMultiCursors,
        Cancel
    }
}
